name: doc_build_workflow

on: 
  push:
    branches:  [ main ]

jobs:
  build_docs:
    runs-on: ubuntu_latest
  steps:  
    - name: Checkout
      uses: actions/checkout@v3    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip        
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Make docs
      run: |
        ./docs/make clean
        ./docs/make html
      with:
      
    - name:
    
